### ISSUE TITLE
Nerd-icons-corfu seems to break alignment in some cases

### ISSUE THREAD

**Issue by minad** [LuigiPiucco/nerd-icons-corfu#13] opened 2024-10-29 22:09 UTC
See problems 1 and 2 described in https://github.com/minad/corfu/pull/508. This issue probably depends on font and icon sizes. The [kind-icon](https://github.com/jdtsmith/kind-icon) package achieves better icon alignment by using exactly two characters for the icon with the icon at the center. Would this work for nerd-icons-corfu too?

**Comment by wyuenho** [comment] 2024-10-30 00:51
It's arguable whether this is a problem for nerd-icon-corfu. As the author of minad/corfu#508, if you read it again from the top, you'll notice I'm demonstrating the problem with all-the-icons SVG branch (of which I'm also the author), which has been in beta since last year. I ran into this issue partially because I had been testing my change's compatibility with the existing ecosystem.

The issue is I'm illustrating is, due to Corfu's imprecise nature WRT to formatting and truncation, ANY icon prefix that does not have the same width as the default font, which is about pretty much any icon, will run into misalignment issues. The current state of affairs creates tremendous difficulty for icon prefix package authors, especially those that do not use icon fonts, but actual images. This implies that icon prefix package authors, or any intrepid Emacs users wanting to customize `corfu-margin-formatters` to know precisely the width of all 21 icons. This may be difficult if the icon images are mixed and matched from different icon sets.

**Comment by minad** [comment] 2024-10-30 09:44
@LuigiPiucco Sorry, I reported this to the wrong package then. ~But can you please confirm that alignment works properly with nerd-icons-corfu? If yes, feel free to close.~

@wyuenho 

> As the author of https://github.com/minad/corfu/pull/508, if you read it again from the top, you'll notice I'm demonstrating the problem with all-the-icons SVG branch (of which I'm also the author), which has been in beta since last year. I ran into this issue partially because I had been testing my change's compatibility with the existing ecosystem.

Thanks. I missed that you are testing with all-the-icons-corfu. I wasn't aware of the existence of this package. I was aware of the other all-the-icons packages but not of all-the-icons-corfu, so I read over this. Could you please also test nerd-icons-corfu to cross check if the problems occur there too?

However it is not arguable if this is a bug in Corfu or all-the-icons-corfu. It is a bug/incompatibility in all-the-icons-corfu simply **by definition of the Corfu margin formatter**. @jdtsmith and I designed the margin formatter this way for the reason that we didn't have pixel precise formatting at hand - as you see it is difficult to achieve. Right now it is a requirement that icon margin formatters return strings with a full character width, which is correctly done by kind-icon.

EDIT: I just checked nerd-icons-corfu and it does indeed cause alignment issues, where the input prompt and the underlying popup are not aligned properly.

**Comment by wyuenho** [comment] 2024-10-30 11:11
>  I missed that you are testing with all-the-icons-corfu. I wasn't aware of the existence of this package.

That's because it doesn't exist. As shown on the very first screenshot on the issue, it's literally just an alist and a curried function, which is the right amount of difficulty a user configuration should be. This package achieves the same result the same way, of which I hadn't looked at the source code.

> I just checked nerd-icons-corfu and it does indeed cause alignment issues, where the input prompt and the underlying popup are not aligned properly.

Indeed, as predicted in my first response, but even if it's misaligned, it's still arguable whether it is a bug in downstream packages, especially if you've documented the requirement just now. Let's just leave other package authors alone for now. When pixel alignment is satisfactorily achieved, or summarily rejected because it cannot be satisfactorily achieved, then we can help other package authors fix their packages.

**Comment by minad** [comment] 2024-10-30 11:34
@wyuenho I am informing other package authors about the requirements as they stand right now. This is not arguable. I am not doing this because I want to push the problems down the line, it is simply an unfortunate technical limitation in Corfu as of now and as it has always been, which cannot be worked around easily.

**Comment by wyuenho** [comment] 2024-10-30 11:44
My suggestion is to wait for a few more weeks as the regressions are ironed out, if the PR is merged, then the issue downstream will be automatically fixed, if not, then we can tell other authors. It's up to you of course.

**Comment by LuigiPiucco** [comment] 2024-10-30 16:19
Sorry I missed the discussion and was unable to help in time, college has kept me busy. Regarding this thread, I've known the issues with alignment, and even tried to fix them locally back when I wrote the package, but as mentioned in https://github.com/minad/corfu/pull/508, the fix wasn't (and still isn't, it seems) simple. My choice at the time was to leave as-is. If you look carefully into the preview screenshot in the README, the closing parenthesis is missing due to it, though perhaps I should be more explicit about the problem.

> The [kind-icon](https://github.com/jdtsmith/kind-icon) package achieves better icon alignment by using exactly two characters for the icon with the icon at the center. Would this work for nerd-icons-corfu too?

I believe I didn't take notice of that back then, and if I recall correctly this package uses three characters. I'll check to see if I can enhance the alignment here, but otherwise close this issue as not planned, since it appears to be a deeply upstream issue (nerd-icons-corfu -> corfu -> Emacs -> Emacs' graphical capabilities...).

@jdtsmith In case you thought I meant kind-icon uses 3 characters, I was referring to nerd-icons-corfu when saying "this package". Sorry if there was confusion due to my phrasing.

**Closed as not planned by LuigiPiucco** 2024-10-30 16:19 UTC

**Comment by jdtsmith** [comment] 2024-10-30 17:17
>  if I recall correctly this package uses three characters

Three characters, with the help of svg-lib. But 2 or even 1 would also work.  BTW, a full solution to minad/corfu#508 isn't required to address the PREFIX/icon alignment _only_.  Since the set of icons is known in advance, their pixel sizes can be pre-computed once (or, e.g., once for every text-scale update), and specified space can be inserted to pad them out to the character boundary or (if desired) `:align-to` the same pixel boundary, as needed.

**Comment by minad** [comment] 2024-10-30 18:42
@LuigiPiucco 

> I believe I didn't take notice of that back then, and if I recall correctly this package uses three characters. I'll check to see if I can enhance the alignment here, but otherwise close this issue as not planned, since it appears to be a deeply upstream issue (nerd-icons-corfu -> corfu -> Emacs -> Emacs' graphical capabilities...).

The deeper issues are certainly upstream, but not fixable as of now. The Emacs display capabilities are a bit weak and inefficient regarding pixel computations. For Corfu it is difficult to work with the given facilities, such that the decision was made early on to make fixed width alignment a requirement for the margin formatters. In the margin formatters the problem can be solved without slowing down the whole Corfu display, since everything can be precomputed as @jdtsmith pointed out. Basically we fail to fix the general problem, but we can fix a subset of the problem in an isolated way.

kind-icon shows that perfect alignment is possible and I am sure someone (maybe @jdtsmith) could give some guidance how to achieve this here too. See also https://github.com/minad/corfu/commit/84a6ece9f6ab3b94e932cfbfe6970a21b59d975c for more details.

But in any case, it is okay to not fix this, if pixel perfect alignment is not a concern for you.

**Comment by jdtsmith** [comment] 2024-10-30 23:34
> @jdtsmith In case you thought I meant kind-icon uses 3 characters, I was referring to nerd-icons-corfu when saying "this package". Sorry if there was confusion due to my phrasing.

No worries, probably my misinterpretation.  If you are interested in "normalizing" the padding of your icons, I think it's a pretty easy process.  Here's an example of measuring pixel widths.   Then you'd pad each icon with specified space to normalize widths.  Doing this once in a mode hook would probably work well.

```elisp
(let ((buf (get-buffer-create " *icons*")))
  (save-window-excursion
    (set-window-buffer nil buf)
    (with-current-buffer buf
      (set (make-local-variable 'face-remapping-alist)
           (copy-tree '((default corfu-default))))
      (erase-buffer)
      (insert "🐜\nα\n😏\nx\n칹\n🐛\n∫\n❄\n") ; user's icons
      (goto-char (point-min))
      (cl-loop 
       while (not (eobp))
       collect (car (window-text-pixel-size nil (pos-bol) (pos-eol)))
       do (forward-line 1)))))
```

**Comment by wyuenho** [comment] 2024-10-31 17:58
> since it appears to be a deeply upstream issue (nerd-icons-corfu -> corfu -> Emacs -> Emacs' graphical capabilities...).

While fundamentally this is a problem emanating from upstream, we need not address it at the source, especially when it's borderline infeasible.

I've just published [corfu-pixel-perfect](https://github.com/wyuenho/emacs-corfu-pixel-perfect), enable `corfu-pixel-perfect-mode` and the issue should go away.

In short, not aligning by pixels cause wide-ranging issues from icons to variable fonts and even the same monospaced font but in a different weight, width or slant.

For those interested, there's a rather long write up in the README specifying what problems it solves, how it solves it, what decisions were made, and how well it works, planned future enhancements and what to do if you find a bug.

Happy Halloween!

**Comment by minad** [comment] 2024-11-01 10:56
@wyuenho 

> This is to honor corfu author's request to not file many issues based on a private conversation. Regardless, I think you'll see a pattern on how he deals with issues by glancing over his repos. I do not intend to cause any additional stress for him.

You do again cause stress on me. I know about my current personal situation. You have been a [bully in the past](https://github.com/melpa/melpa/pull/7215#issuecomment-933016169) and you do it again, after I unblocked you on Github. For some reason you need to be right despite all the costs. Note that @jdtsmith has noted that your quick reactions in your PR were a problem to collaborate effectively. If you do not want to cause stress on me, then I suggest to tone down in the README of corfu-pixel-perfect.
